DROP TABLE IF EXISTS MEMBER_LOGIN CASCADE;
DROP TABLE IF EXISTS MEMBER CASCADE;
DROP TABLE IF EXISTS CREDIT_TYPE CASCADE;
DROP TABLE IF EXISTS FLIGHT_MASTER CASCADE;
DROP TABLE IF EXISTS FLIGHT CASCADE;
DROP TABLE IF EXISTS RESERVE_FLIGHT CASCADE;
DROP TABLE IF EXISTS RESERVATION CASCADE;
DROP TABLE IF EXISTS ROUTE CASCADE;
DROP TABLE IF EXISTS BOARDING_CLASS CASCADE;
DROP TABLE IF EXISTS PASSENGER CASCADE;
DROP TABLE IF EXISTS AIRPORT CASCADE;
DROP TABLE IF EXISTS PLANE CASCADE;
DROP TABLE IF EXISTS FARE_TYPE CASCADE;
DROP TABLE IF EXISTS PEAK_TIME CASCADE;

DROP SEQUENCE IF EXISTS SQ_MEMBER_1;
DROP SEQUENCE IF EXISTS SQ_RESERVATION_1;
DROP SEQUENCE IF EXISTS SQ_RESERVE_FLIGHT_1;
DROP SEQUENCE IF EXISTS SQ_PASSENGER_1;
